### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by payalshah01** [shabbyrobe/phphll#1]
Hello, 

Do we have support for PHP 7 version ??

**Comment by DanishQamar** [comment]
Hi Please provide support for php7 as I am migrating to php7 on my servers and not able to use this library..

Thanks in advance..

**Comment by shabbyrobe** [comment]
Definitely. It's a work in progress. Hopefully have something for you soon.

**Comment by payalshah01** [comment]
Need php7 support, till when it will be done?

**Comment by shabbyrobe** [comment]
I haven't needed it myself and I've been busy with other things for a while. It's funny that you should comment on this issue though, as I was just thinking earlier today I should go through and clean up my old PHP code so it still works. I can't make any promises around timing, but I do agree it needs to be done and will start to look into it.

**Comment by payalshah01** [comment]
Thanks a lot. I will be waiting for your reply.

**Comment by shabbyrobe** [comment]
OK I've got the first pass of PHP7 support working. All tests pass, no memory leaks. No guarantees that it's 100% - please file any issues you run into separately. Good luck!

**Comment by payalshah01** [comment]
Thanks a lot, I will download and test and get back you incase of any issue.

**Comment by payalshah01** [comment]
Thanks for updated version. me and my colleague Geeta tested HLL functionality, on Both version  (PHP7 and PHP 5.4.5) counts are matching.
